{% set name = "aiorun" %}
{% set version = "2022.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d820cebffdea82f9c1750cc396f3a58e4c0d277a2c51f11e86ed6ab7736dce59

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
    - flit
  run:
    - python >=3.5

test:
  imports:
    - aiorun

about:
  home: https://github.com/cjrh/aiorun
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A "run" function for asyncio-based apps that does all the boilerplate.

extra:
  recipe-maintainers:
    - scopatz
