travis:
  secure:
    BINSTAR_TOKEN: O2BP4D5wpO75MpNx0Q2QbZku2lz7kH1bKkyaD2PZBvjnvMoQNEbEwP8PlqF4cR9Vwj6woQr7RlbvQj43zTr/Phx8bmmYiuTbBYqzMtpT4wO7ehtR3aFsfg6wHmeFqz229D8wSLPirhz48G/CnOhLt92JQ9miYjhyThYacMPIPFzwo3hOhtmGb9nj6FFZ+bvwstrrfrzxgdUGtBRGE4+aN2L+Fp0Px4+fHDdSuDG5oxbtaA6XdwhO+mxQueXuhXgvh9CAXIUQkQ6zEeyKLkWAGPljJ2UsGDtiZ1nVXZnp7f18VSrXHj8yBKp8/RaYm3QcfxVdoMcWjJUuMoFf4nXwblOwpp0L6lafsqlYw1q0vV6l+2Kg6lTZSrDaB79T5NNNuJr/xlD9ldVp1okQxGIb8INVlPQSbvlVeetc5J18/OGmvguf6iLXqg+zTuuLjFlpJXFo8OEie01WaxRxWXThj7MWBKj5dc5JYkB6iulhewN8PQ7YzbRu/jJQ54vv7iy3JvQIdWr6QcR+KZ/TduAbn8Z7dZLjK/7lLaJFhnNbrfXc0t9bokn2yZ3q5n738XQtRDzzxguWFihozuyTlt4pR/CWSlWmARhBemi3wXiJVUdNMceRy3p6qOtJSBC1NCY2M1RhZxATmveOh/OHRzzMao5qDfy51iGHC1CmUFV3PN4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
